### ISSUE TITLE
JavaScript Capstone Project

### ISSUE THREAD

**Issue by DhuruvSingh** [DhuruvSingh/CapstoneJS#21]
- Copied the project template
- Decided who is gonna be A and B (We are 2 people on this team)
- A is gonna be @DhuruvSingh
- B is gonna be @Peter1907 
- Assigned each one to his respective tasks
- Implemented the changes required by the previous code reviewer

The project's link: https://github.com/DhuruvSingh/CapstoneJS/projects/1

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @DhuruvSingh, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Kanban board complete. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] You should provide the link to the Kanban board project. Please use the correct link in this issue.
- [ ] I see that you assigned the students correctly but you left the `Student C` cards when they should be removed. Kindly remove them as this is a project requirement.
<img width="613" alt="image" src="https://user-images.githubusercontent.com/61919617/188672325-3b878734-78bf-4c37-be00-82584a21fe1c.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DeliceLydia** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
 # Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
